<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>찾아줘문서</AssemblyName>
    <RootNamespace>SearchDoc</RootNamespace>
    <Version>2.0.0</Version>
    <FileVersion>2.0.0.0</FileVersion>
    <Product>찾아줘문서</Product>
    <AssemblyTitle>파일 찾다가 답답해서 내가 만든 프로그램</AssemblyTitle>
    <FileDescription>파일 찾다가 답답해서 내가 만든 프로그램</FileDescription>
    <Description>파일 찾다가 답답해서 내가 만든 프로그램</Description>
    <Company>전진우</Company>
    <Authors>전진우</Authors>
    <ApplicationTitle>찾아줘문서</ApplicationTitle>
    <ApplicationIcon>Assets\searchdoc.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\searchdoc.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\info_icon.png" />
  </ItemGroup>

</Project>
